spring:
  application:
    name: ingestor
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring,json.add.type.headers: false

server:
  port: 8080

app:
  binance:
    base-url: https://api.binance.com
  ingestion:
    symbols: ["ETHUSDT", "BNBUSDT"]
    interval: "1h"
    limit: 1000
    pool-seconds: 600
  kafka:
    candles-topic: market.candles
